// <auto-generated />
using System;
using System.Collections.Generic;
using System.Text.Json;
using LocalList.API.NET.Shared.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace LocalList.API.NET.Migrations
{
    [DbContext(typeof(LocalListDbContext))]
    [Migration("20260713170724_AddBillingEvents")]
    partial class AddBillingEvents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LocalList.API.NET.Shared.Data.Entities.BillingEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AppUserId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("app_user_id");

                    b.Property<long>("EventTimestampMs")
                        .HasColumnType("bigint")
                        .HasColumnName("event_timestamp_ms");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("RcEventId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("rc_event_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("RcEventId")
                        .IsUnique();

                    b.HasIndex("UserId", "EventTimestampMs");

                    b.ToTable("billing_events");
                });

            modelBuilder.Entity("LocalList.API.NET.Shared.Data.Entities.ChatSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AnonymousIpHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("anonymous_ip_hash");

                    b.Property<Guid?>("GeneratedPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("generated_plan_id");

                    b.Property<string>("HistoryJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("history");

                    b.PrimitiveCollection<string[]>("LastOfferedChips")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("last_offered_chips");

                    b.Property<DateTimeOffset>("LastTurnAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_turn_at");

                    b.Property<string>("SlotsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slots");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("SuspicionJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("suspicion");

                    b.Property<int>("TurnCount")
                        .HasColumnType("integer")
                        .HasColumnName("turn_count");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("AnonymousIpHash");

                    b.HasIndex("LastTurnAt");

                    b.HasIndex("UserId", "Status");

                    b.ToTable("chat_sessions");
                });

            modelBuilder.Entity("LocalList.API.NET.Shared.Data.Entities.ChatTurn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AiProvider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ai_provider");

                    b.Property<string>("ContextSignalsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("context_signals");

                    b.Property<decimal?>("CostUsd")
                        .HasColumnType("numeric")
                        .HasColumnName("cost_usd");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorCode")
                        .HasColumnType("text")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("FinishReason")
                        .HasColumnType("text")
                        .HasColumnName("finish_reason");

                    b.Property<int?>("GeminiStatus")
                        .HasColumnType("integer")
                        .HasColumnName("gemini_status");

                    b.Property<int?>("InputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("input_tokens");

                    b.Property<int>("LatencyMs")
                        .HasColumnType("integer")
                        .HasColumnName("latency_ms");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<int?>("OutputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("output_tokens");

                    b.Property<int>("PromptChars")
                        .HasColumnType("integer")
                        .HasColumnName("prompt_chars");

                    b.Property<string>("PromptExcerpt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prompt_excerpt");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prompt_version");

                    b.Property<string>("QuickReplyId")
                        .HasColumnType("text")
                        .HasColumnName("quick_reply_id");

                    b.Property<bool>("Regenerated")
                        .HasColumnType("boolean")
                        .HasColumnName("regenerated");

                    b.Property<string>("ResponseRaw")
                        .HasColumnType("text")
                        .HasColumnName("response_raw");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<short?>("SlotCompleteness")
                        .HasColumnType("smallint")
                        .HasColumnName("slot_completeness");

                    b.Property<int?>("ThinkingTokens")
                        .HasColumnType("integer")
                        .HasColumnName("thinking_tokens");

                    b.Property<int?>("TotalTokens")
                        .HasColumnType("integer")
                        .HasColumnName("total_tokens");

                    b.Property<string>("TraceId")
                        .HasColumnType("text")
                        .HasColumnName("trace_id");

                    b.Property<int>("TurnIndex")
                        .HasColumnType("integer")
                        .HasColumnName("turn_index");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("UserMessage")
                        .HasColumnType("text")
                        .HasColumnName("user_message");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("PromptVersion", "CreatedAt");

                    b.HasIndex("SessionId", "TurnIndex")
                        .IsUnique()
                        .HasFilter("session_id IS NOT NULL");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("chat_turns");
                });

            modelBuilder.Entity("LocalList.API.NET.Shared.Data.Entities.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Country")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("country");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("normalized_name");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("cities");
                });

            modelBuilder.Entity("LocalList.API.NET.Shared.Data.Entities.FollowSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<int>("CurrentDayIndex")
                        .HasColumnType("integer")
                        .HasColumnName("current_day_index");

                    b.Property<int>("CurrentStopIndex")
                        .HasColumnType("integer")
                        .HasColumnName("current_stop_index");

                    b.Property<DateTimeOffset>("LastActiveAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_active_at");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("UserId", "Status");

                    b.ToTable("follow_sessions");
                });

            modelBuilder.Entity("LocalList.API.NET.Shared.Data.Entities.Place", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("AiVibeScore")
                        .HasColumnType("integer")
                        .HasColumnName("ai_vibe_score");

                    b.PrimitiveCollection<List<string>>("BestFor")
                        .HasColumnType("text[]")
                        .HasColumnName("best_for");

                    b.Property<JsonDocument>("BestForI18n")
                        .HasColumnType("jsonb")
                        .HasColumnName("best_for_i18n");

                    b.PrimitiveCollection<List<string>>("BestTimes")
                        .HasColumnType("text[]")
                        .HasColumnName("best_times");

                    b.Property<JsonDocument>("BestTimesI18n")
                        .HasColumnType("jsonb")
                        .HasColumnName("best_times_i18n");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(768)")
                        .HasColumnName("embedding");

                    b.PrimitiveCollection<List<string>>("Flags")
                        .HasColumnType("text[]")
                        .HasColumnName("flags");

                    b.Property<string>("GooglePlaceId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("google_place_id");

                    b.Property<decimal?>("GoogleRating")
                        .HasColumnType("decimal(2, 1)")
                        .HasColumnName("google_rating");

                    b.Property<int?>("GoogleReviewCount")
                        .HasColumnType("integer")
                        .HasColumnName("google_review_count");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(10, 7)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(10, 7)")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<JsonDocument>("NameI18n")
                        .HasColumnType("jsonb")
                        .HasColumnName("name_i18n");

                    b.Property<string>("Neighborhood")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("neighborhood");

                    b.Property<JsonDocument>("NeighborhoodI18n")
                        .HasColumnType("jsonb")
                        .HasColumnName("neighborhood_i18n");

                    b.Property<JsonDocument>("OpeningHours")
                        .HasColumnType("jsonb")
                        .HasColumnName("opening_hours");

                    b.PrimitiveCollection<List<string>>("Photos")
                        .HasColumnType("text[]")
                        .HasColumnName("photos");

                    b.Property<string>("PriceRange")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("price_range");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("rejection_reason");

                    b.Property<DateTimeOffset?>("ReviewDeferredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("review_deferred_at");

                    b.Property<Guid?>("ReviewedById")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("text")
                        .HasColumnName("source_url");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.PrimitiveCollection<List<string>>("Subcategories")
                        .HasColumnType("text[]")
                        .HasColumnName("subcategories");

                    b.Property<JsonDocument>("SubcategoriesI18n")
                        .HasColumnType("jsonb")
                        .HasColumnName("subcategories_i18n");

                    b.Property<Guid?>("SubmittedById")
                        .HasColumnType("uuid")
                        .HasColumnName("submitted_by");

                    b.PrimitiveCollection<List<string>>("SuitableFor")
                        .HasColumnType("text[]")
                        .HasColumnName("suitable_for");

                    b.Property<JsonDocument>("SuitableForI18n")
                        .HasColumnType("jsonb")
                        .HasColumnName("suitable_for_i18n");

                    b.Property<JsonDocument>("TranslationStatus")
                        .HasColumnType("jsonb")
                        .HasColumnName("translation_status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("VisitDurationMin")
                        .HasColumnType("integer")
                        .HasColumnName("visit_duration_min");

                    b.Property<string>("WhyThisPlace")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("why_this_place");

                    b.Property<JsonDocument>("WhyThisPlaceI18n")
                        .HasColumnType("jsonb")
                        .HasColumnName("why_this_place_i18n");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("GooglePlaceId")
                        .IsUnique();

                    b.HasIndex("ReviewedById");

                    b.HasIndex("SubmittedById");

                    b.HasIndex("Status", "City");

                    b.ToTable("places");
                });

            modelBuilder.Entity("LocalList.API.NET.Shared.Data.Entities.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<JsonDocument>("DescriptionI18n")
                        .HasColumnType("jsonb")
                        .HasColumnName("description_i18n");

                    b.Property<int>("DurationDays")
                        .HasColumnType("integer")
                        .HasColumnName("duration_days");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<bool>("IsShowcase")
                        .HasColumnType("boolean")
                        .HasColumnName("is_showcase");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<JsonDocument>("NameI18n")
                        .HasColumnType("jsonb")
                        .HasColumnName("name_i18n");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.Property<JsonDocument>("TranslationStatus")
                        .HasColumnType("jsonb")
                        .HasColumnName("translation_status");

                    b.Property<JsonDocument>("TripContext")
                        .HasColumnType("jsonb")
                        .HasColumnName("trip_context");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("City", "IsPublic");

                    b.ToTable("plans");
                });

            modelBuilder.Entity("LocalList.API.NET.Shared.Data.Entities.PlanMetric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AiProvider")
                        .HasColumnType("text")
                        .HasColumnName("ai_provider");

                    b.Property<string>("Budget")
                        .HasColumnType("text")
                        .HasColumnName("budget");

                    b.Property<Guid?>("ChatSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("chat_session_id");

                    b.Property<decimal?>("CostUsd")
                        .HasColumnType("numeric")
                        .HasColumnName("cost_usd");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("EditedCount")
                        .HasColumnType("integer")
                        .HasColumnName("edited_count");

                    b.Property<DateTimeOffset?>("FollowedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("followed_at");

                    b.Property<Guid?>("GenerateTurnId")
                        .HasColumnType("uuid")
                        .HasColumnName("generate_turn_id");

                    b.Property<string>("GenerationSource")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("generation_source");

                    b.Property<string>("GroupType")
                        .HasColumnType("text")
                        .HasColumnName("group_type");

                    b.Property<int>("LatencyMs")
                        .HasColumnType("integer")
                        .HasColumnName("latency_ms");

                    b.Property<int>("NumCategories")
                        .HasColumnType("integer")
                        .HasColumnName("num_categories");

                    b.Property<int>("NumDays")
                        .HasColumnType("integer")
                        .HasColumnName("num_days");

                    b.Property<int>("NumStops")
                        .HasColumnType("integer")
                        .HasColumnName("num_stops");

                    b.Property<DateTimeOffset?>("OpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<string>("PromptVersion")
                        .HasColumnType("text")
                        .HasColumnName("prompt_version");

                    b.Property<bool>("Regenerated")
                        .HasColumnType("boolean")
                        .HasColumnName("regenerated");

                    b.Property<short>("SignalsFilled")
                        .HasColumnType("smallint")
                        .HasColumnName("signals_filled");

                    b.Property<string>("VibesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("vibes_json");

                    b.Property<bool>("WasFollowed")
                        .HasColumnType("boolean")
                        .HasColumnName("was_followed");

                    b.Property<bool>("WasOpened")
                        .HasColumnType("boolean")
                        .HasColumnName("was_opened");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("PlanId")
                        .IsUnique();

                    b.HasIndex("GenerationSource", "CreatedAt");

                    b.HasIndex("PromptVersion", "CreatedAt");

                    b.ToTable("plan_metrics");
                });

            modelBuilder.Entity("LocalList.API.NET.Shared.Data.Entities.PlanStop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DayNumber")
                        .HasColumnType("integer")
                        .HasColumnName("day_number");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.Property<Guid>("PlaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("place_id");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<TimeSpan?>("SuggestedArrival")
                        .HasColumnType("interval")
                        .HasColumnName("suggested_arrival");

                    b.Property<int?>("SuggestedDurationMin")
                        .HasColumnType("integer")
                        .HasColumnName("suggested_duration_min");

                    b.Property<string>("TimeBlock")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("time_block");

                    b.Property<JsonDocument>("TravelFromPrevious")
                        .HasColumnType("jsonb")
                        .HasColumnName("travel_from_previous");

                    b.HasKey("Id");

                    b.HasIndex("PlaceId");

                    b.HasIndex("PlanId", "DayNumber");

                    b.ToTable("plan_stops");
                });

            modelBuilder.Entity("LocalList.API.NET.Shared.Data.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("token_hash");

                    b.Property<string>("TokenPrefix")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("token_prefix");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TokenPrefix");

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens");
                });

            modelBuilder.Entity("LocalList.API.NET.Shared.Data.Entities.RouteSegmentCache", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("computed_at");

                    b.Property<int>("DistanceMeters")
                        .HasColumnType("integer")
                        .HasColumnName("distance_meters");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_seconds");

                    b.Property<string>("EncodedPolyline")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("encoded_polyline");

                    b.Property<Guid>("FromPlaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_place_id");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("mode");

                    b.Property<Guid>("ToPlaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_place_id");

                    b.HasKey("Id");

                    b.HasIndex("ToPlaceId");

                    b.HasIndex("FromPlaceId", "ToPlaceId", "Mode")
                        .IsUnique();

                    b.ToTable("route_segment_cache");
                });

            modelBuilder.Entity("LocalList.API.NET.Shared.Data.Entities.Subcategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CategoryKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category_key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByAdminUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_admin_user_id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("key");

                    b.Property<string>("LabelEn")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("label_en");

                    b.Property<string>("LabelEs")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("label_es");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CategoryKey", "Key")
                        .IsUnique()
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("subcategories");
                });

            modelBuilder.Entity("LocalList.API.NET.Shared.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AppleUserId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("apple_user_id");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirebaseUid")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("firebase_uid");

                    b.Property<string>("GoogleUserId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("google_user_id");

                    b.Property<string>("Image")
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("RcCustomerId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("rc_customer_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tier");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AppleUserId")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("FirebaseUid")
                        .IsUnique();

                    b.HasIndex("GoogleUserId")
                        .IsUnique();

                    b.HasIndex("RcCustomerId")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("LocalList.API.NET.Shared.Data.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.PrimitiveCollection<List<string>>("CompanionTags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("companion_tags");

                    b.Property<string>("DefaultBudgetTier")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("default_budget_tier");

                    b.Property<string>("DefaultGroupType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("default_group_type");

                    b.PrimitiveCollection<List<string>>("DietaryRestrictions")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("dietary_restrictions");

                    b.Property<string>("FavoriteCity")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("favorite_city");

                    b.Property<string>("PacePreference")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("pace_preference");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId");

                    b.ToTable("user_profiles");
                });

            modelBuilder.Entity("LocalList.API.NET.Shared.Data.Entities.WaitlistEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AnonymousId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("anonymous_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Fbclid")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("fbclid");

                    b.Property<DateTimeOffset?>("FirstTouchAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_touch_at");

                    b.Property<string>("Gclid")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("gclid");

                    b.Property<string>("IpHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_hash");

                    b.Property<string>("LandingPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("landing_path");

                    b.Property<DateTimeOffset?>("LastTouchAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_touch_at");

                    b.Property<string>("Referrer")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("referrer");

                    b.Property<string>("Ttclid")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ttclid");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_agent");

                    b.Property<string>("UtmCampaign")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("utm_campaign");

                    b.Property<string>("UtmContent")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("utm_content");

                    b.Property<string>("UtmMedium")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("utm_medium");

                    b.Property<string>("UtmSource")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("utm_source");

                    b.Property<string>("UtmTerm")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("utm_term");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("waitlist_entries");
                });

            modelBuilder.Entity("LocalList.API.NET.Shared.Data.Entities.ChatSession", b =>
                {
                    b.HasOne("LocalList.API.NET.Shared.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("LocalList.API.NET.Shared.Data.Entities.ChatTurn", b =>
                {
                    b.HasOne("LocalList.API.NET.Shared.Data.Entities.ChatSession", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LocalList.API.NET.Shared.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Session");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LocalList.API.NET.Shared.Data.Entities.FollowSession", b =>
                {
                    b.HasOne("LocalList.API.NET.Shared.Data.Entities.Plan", "Plan")
                        .WithMany("FollowSessions")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LocalList.API.NET.Shared.Data.Entities.User", "User")
                        .WithMany("FollowSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LocalList.API.NET.Shared.Data.Entities.Place", b =>
                {
                    b.HasOne("LocalList.API.NET.Shared.Data.Entities.User", "ReviewedBy")
                        .WithMany("ReviewedPlaces")
                        .HasForeignKey("ReviewedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LocalList.API.NET.Shared.Data.Entities.User", "SubmittedBy")
                        .WithMany("SubmittedPlaces")
                        .HasForeignKey("SubmittedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ReviewedBy");

                    b.Navigation("SubmittedBy");
                });

            modelBuilder.Entity("LocalList.API.NET.Shared.Data.Entities.Plan", b =>
                {
                    b.HasOne("LocalList.API.NET.Shared.Data.Entities.User", "CreatedBy")
                        .WithMany("CreatedPlans")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("LocalList.API.NET.Shared.Data.Entities.PlanMetric", b =>
                {
                    b.HasOne("LocalList.API.NET.Shared.Data.Entities.Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("LocalList.API.NET.Shared.Data.Entities.PlanStop", b =>
                {
                    b.HasOne("LocalList.API.NET.Shared.Data.Entities.Place", "Place")
                        .WithMany("PlanStops")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LocalList.API.NET.Shared.Data.Entities.Plan", "Plan")
                        .WithMany("Stops")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Place");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("LocalList.API.NET.Shared.Data.Entities.RefreshToken", b =>
                {
                    b.HasOne("LocalList.API.NET.Shared.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LocalList.API.NET.Shared.Data.Entities.RouteSegmentCache", b =>
                {
                    b.HasOne("LocalList.API.NET.Shared.Data.Entities.Place", "FromPlace")
                        .WithMany()
                        .HasForeignKey("FromPlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LocalList.API.NET.Shared.Data.Entities.Place", "ToPlace")
                        .WithMany()
                        .HasForeignKey("ToPlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromPlace");

                    b.Navigation("ToPlace");
                });

            modelBuilder.Entity("LocalList.API.NET.Shared.Data.Entities.UserProfile", b =>
                {
                    b.HasOne("LocalList.API.NET.Shared.Data.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("LocalList.API.NET.Shared.Data.Entities.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LocalList.API.NET.Shared.Data.Entities.Place", b =>
                {
                    b.Navigation("PlanStops");
                });

            modelBuilder.Entity("LocalList.API.NET.Shared.Data.Entities.Plan", b =>
                {
                    b.Navigation("FollowSessions");

                    b.Navigation("Stops");
                });

            modelBuilder.Entity("LocalList.API.NET.Shared.Data.Entities.User", b =>
                {
                    b.Navigation("CreatedPlans");

                    b.Navigation("FollowSessions");

                    b.Navigation("ReviewedPlaces");

                    b.Navigation("SubmittedPlaces");
                });
#pragma warning restore 612, 618
        }
    }
}
