using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LocalList.API.NET.Migrations
{
    /// <inheritdoc />
    public partial class AddWaitlistEntries : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS waitlist_entries (
                    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    email character varying(255) NOT NULL,
                    created_at timestamp with time zone NOT NULL,
                    CONSTRAINT "PK_waitlist_entries" PRIMARY KEY (id)
                );
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_waitlist_entries_email"
                    ON waitlist_entries (email);
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "waitlist_entries");
        }
    }
}
