// <auto-generated />
using System;
using System.Collections.Generic;
using System.Text.Json;
using LocalList.API.NET.Shared.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LocalList.API.NET.Migrations
{
    [DbContext(typeof(LocalListDbContext))]
    [Migration("20260331173441_AddWaitlistEntries")]
    partial class AddWaitlistEntries
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LocalList.API.NET.Shared.Data.Entities.FollowSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<int>("CurrentDayIndex")
                        .HasColumnType("integer")
                        .HasColumnName("current_day_index");

                    b.Property<int>("CurrentStopIndex")
                        .HasColumnType("integer")
                        .HasColumnName("current_stop_index");

                    b.Property<DateTimeOffset>("LastActiveAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_active_at");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("UserId", "Status");

                    b.ToTable("follow_sessions");
                });

            modelBuilder.Entity("LocalList.API.NET.Shared.Data.Entities.Place", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("AiVibeScore")
                        .HasColumnType("integer")
                        .HasColumnName("ai_vibe_score");

                    b.PrimitiveCollection<List<string>>("BestFor")
                        .HasColumnType("text[]")
                        .HasColumnName("best_for");

                    b.Property<string>("BestTime")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("best_time");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.PrimitiveCollection<List<string>>("Flags")
                        .HasColumnType("text[]")
                        .HasColumnName("flags");

                    b.Property<string>("GooglePlaceId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("google_place_id");

                    b.Property<decimal?>("GoogleRating")
                        .HasColumnType("decimal(2, 1)")
                        .HasColumnName("google_rating");

                    b.Property<int?>("GoogleReviewCount")
                        .HasColumnType("integer")
                        .HasColumnName("google_review_count");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(10, 7)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(10, 7)")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Neighborhood")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("neighborhood");

                    b.Property<JsonDocument>("OpeningHours")
                        .HasColumnType("jsonb")
                        .HasColumnName("opening_hours");

                    b.PrimitiveCollection<List<string>>("Photos")
                        .HasColumnType("text[]")
                        .HasColumnName("photos");

                    b.Property<string>("PriceRange")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("price_range");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("rejection_reason");

                    b.Property<Guid?>("ReviewedById")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("text")
                        .HasColumnName("source_url");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Subcategory")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("subcategory");

                    b.Property<Guid?>("SubmittedById")
                        .HasColumnType("uuid")
                        .HasColumnName("submitted_by");

                    b.PrimitiveCollection<List<string>>("SuitableFor")
                        .HasColumnType("text[]")
                        .HasColumnName("suitable_for");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WhyThisPlace")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("why_this_place");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("GooglePlaceId")
                        .IsUnique();

                    b.HasIndex("ReviewedById");

                    b.HasIndex("SubmittedById");

                    b.HasIndex("Status", "City");

                    b.ToTable("places");
                });

            modelBuilder.Entity("LocalList.API.NET.Shared.Data.Entities.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("DurationDays")
                        .HasColumnType("integer")
                        .HasColumnName("duration_days");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<bool>("IsShowcase")
                        .HasColumnType("boolean")
                        .HasColumnName("is_showcase");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<JsonDocument>("TripContext")
                        .HasColumnType("jsonb")
                        .HasColumnName("trip_context");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("City", "IsPublic");

                    b.ToTable("plans");
                });

            modelBuilder.Entity("LocalList.API.NET.Shared.Data.Entities.PlanStop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DayNumber")
                        .HasColumnType("integer")
                        .HasColumnName("day_number");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.Property<Guid>("PlaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("place_id");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<TimeSpan?>("SuggestedArrival")
                        .HasColumnType("interval")
                        .HasColumnName("suggested_arrival");

                    b.Property<int?>("SuggestedDurationMin")
                        .HasColumnType("integer")
                        .HasColumnName("suggested_duration_min");

                    b.Property<string>("TimeBlock")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("time_block");

                    b.Property<JsonDocument>("TravelFromPrevious")
                        .HasColumnType("jsonb")
                        .HasColumnName("travel_from_previous");

                    b.HasKey("Id");

                    b.HasIndex("PlaceId");

                    b.HasIndex("PlanId", "DayNumber");

                    b.ToTable("plan_stops");
                });

            modelBuilder.Entity("LocalList.API.NET.Shared.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AppleUserId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("apple_user_id");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirebaseUid")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("firebase_uid");

                    b.Property<string>("GoogleUserId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("google_user_id");

                    b.Property<string>("Image")
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("RcCustomerId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("rc_customer_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tier");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AppleUserId")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("FirebaseUid")
                        .IsUnique();

                    b.HasIndex("GoogleUserId")
                        .IsUnique();

                    b.HasIndex("RcCustomerId")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("LocalList.API.NET.Shared.Data.Entities.WaitlistEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("waitlist_entries");
                });

            modelBuilder.Entity("LocalList.API.NET.Shared.Data.Entities.FollowSession", b =>
                {
                    b.HasOne("LocalList.API.NET.Shared.Data.Entities.Plan", "Plan")
                        .WithMany("FollowSessions")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LocalList.API.NET.Shared.Data.Entities.User", "User")
                        .WithMany("FollowSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LocalList.API.NET.Shared.Data.Entities.Place", b =>
                {
                    b.HasOne("LocalList.API.NET.Shared.Data.Entities.User", "ReviewedBy")
                        .WithMany("ReviewedPlaces")
                        .HasForeignKey("ReviewedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LocalList.API.NET.Shared.Data.Entities.User", "SubmittedBy")
                        .WithMany("SubmittedPlaces")
                        .HasForeignKey("SubmittedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ReviewedBy");

                    b.Navigation("SubmittedBy");
                });

            modelBuilder.Entity("LocalList.API.NET.Shared.Data.Entities.Plan", b =>
                {
                    b.HasOne("LocalList.API.NET.Shared.Data.Entities.User", "CreatedBy")
                        .WithMany("CreatedPlans")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("LocalList.API.NET.Shared.Data.Entities.PlanStop", b =>
                {
                    b.HasOne("LocalList.API.NET.Shared.Data.Entities.Place", "Place")
                        .WithMany("PlanStops")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LocalList.API.NET.Shared.Data.Entities.Plan", "Plan")
                        .WithMany("Stops")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Place");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("LocalList.API.NET.Shared.Data.Entities.Place", b =>
                {
                    b.Navigation("PlanStops");
                });

            modelBuilder.Entity("LocalList.API.NET.Shared.Data.Entities.Plan", b =>
                {
                    b.Navigation("FollowSessions");

                    b.Navigation("Stops");
                });

            modelBuilder.Entity("LocalList.API.NET.Shared.Data.Entities.User", b =>
                {
                    b.Navigation("CreatedPlans");

                    b.Navigation("FollowSessions");

                    b.Navigation("ReviewedPlaces");

                    b.Navigation("SubmittedPlaces");
                });
#pragma warning restore 612, 618
        }
    }
}
