name: .NET CI & Security

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-security:
    name: Build & Security Audit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore LocalList.API.slnx

      - name: Build
        run: dotnet build LocalList.API.slnx --no-restore

      - name: Test
        run: dotnet test LocalList.API.slnx --no-build --verbosity normal
